export interface Project {
  id: string;
  title: string;
  location: string;
  year: string;
  category: 'Professional' | 'Academic' | 'Other Works';
  subCategory?: 'Residential' | 'Training' | 'Urban' | 'Research';
  role: string;
  description: string;
  heroImage: string;
  images: string[];
  concept?: string;
  process?: string;
  drawings?: string;
  execution?: string;
  reflection?: string;
}

export const projects: Project[] = [
  {
    id: 'whitefield-society',
    title: 'Residence at Whitefield Society',
    location: 'Indore, Madhya Pradesh',
    year: '2023',
    category: 'Professional',
    subCategory: 'Residential',
    role: 'Senior Architect — Design & Execution',
    description: 'A comprehensive interior design and execution project for a luxury residence, encompassing living spaces, bedrooms, courtyards, and custom detailing.',
    heroImage: '/images/project-whitefield-hero.jpg',
    images: ['/images/project-whitefield-1.jpg', '/images/project-whitefield-2.jpg'],
    concept: 'The design concept centered on creating a seamless flow between indoor and outdoor spaces, using natural materials and warm lighting to evoke a sense of calm luxury. The double-height living area became the focal point, anchored by a statement chandelier and floor-to-ceiling windows.',
    process: 'The process began with extensive client consultations to understand their lifestyle and preferences. Multiple design iterations were explored through hand sketches and 3D visualizations before finalizing the material palette and spatial layout.',
    drawings: 'Working drawings included detailed floor plans, reflected ceiling plans, electrical layouts, and custom joinery details. Wall panelling details, flooring patterns, and lighting layouts were developed with precision.',
    execution: 'The execution phase involved close coordination with contractors and vendors. Material selection and sourcing were critical — from imported marble to custom furniture pieces. Regular site inspections ensured quality at every stage.',
    reflection: 'This project taught me the importance of detailing in interior architecture. Every junction, every material transition, and every lighting placement contributes to the overall experience of the space.',
  },
  {
    id: 'ratlam-kothi',
    title: 'Residence at Ratlam Kothi',
    location: 'Indore, Madhya Pradesh',
    year: '2023',
    category: 'Professional',
    subCategory: 'Residential',
    role: 'Senior Architect — Interior Architecture',
    description: 'Interior design and renovation of a residence, blending contemporary aesthetics with the existing structural elements.',
    heroImage: '/images/project-ratlam-hero.jpg',
    images: ['/images/project-ratlam-1.jpg'],
    concept: 'The design approach was sensitive to the existing structure, accommodating and concealing structural elements without compromising space. Foldable furniture and flexible design interventions maximized the usable area.',
    process: 'Close collaboration with the client helped understand their needs. The design balanced modern aesthetics with practical considerations, using a neutral color palette with subtle pops of color.',
    drawings: 'Working drawings included detailed interior layouts, wall panelling details, flooring patterns, lighting layouts, and custom furniture designs.',
    execution: 'Material selection and vendor coordination were key aspects. The project involved sourcing unique materials and coordinating with multiple contractors to achieve a cohesive design.',
    reflection: 'Renovation projects require a different mindset — working with what exists and finding creative solutions within constraints. This project sharpened my problem-solving skills.',
  },
  {
    id: 'sanika-apartments',
    title: 'Apartments for Sanika Developers',
    location: 'Belgaum, Karnataka',
    year: '2021',
    category: 'Professional',
    subCategory: 'Training',
    role: 'Intern Architect — Thirdspace Architecture Studio',
    description: 'A residential apartment project on a 19,000 sq ft site, featuring contemporary elevation design with innovative circular pattern facade systems.',
    heroImage: '/images/project-sanika-hero.jpg',
    images: ['/images/project-sanika-1.jpg'],
    concept: 'The elevation design explored patterns generated by circular openings at a regular grid, with diameters varying to create visual interest. The concept was to bring artistry to the facade while maintaining functional requirements.',
    process: 'The internship involved elevation design, 3D rendering, area statements, 2D drawings, sanction drawings, and structural framing drawings. Twinmotion was used for real-time visualization.',
    drawings: 'Working drawings included floor plans, elevation details with the circular pattern system, structural framing layouts, and sanction drawings for municipal approval.',
    execution: 'The project provided hands-on experience in the complete documentation process for a residential development, from concept to sanction stage.',
    reflection: 'This internship was my first professional exposure to the architecture industry. It taught me the importance of technical precision and the value of collaborative work in a studio environment.',
  },
  {
    id: 'eco-tourism',
    title: 'Eco Tourism Facility',
    location: 'Polo Forest, Gujarat',
    year: '2022',
    category: 'Academic',
    subCategory: 'Research',
    role: 'Student Architect — Semester 9 Design Studio',
    description: 'An eco-tourism facility designed to blend with the natural landscape of Polo Forest, offering accommodation, research labs, exhibition galleries, and viewing decks.',
    heroImage: '/images/project-eco-hero.jpg',
    images: ['/images/project-eco-1.jpg', '/images/project-eco-2.jpg'],
    concept: 'The concept emerged from a deep study of the site — its topography, vegetation, and natural water streams. The built form was designed to merge with the landscape, using a porous envelope that is bold yet not dominating.',
    process: 'Extensive site analysis informed the placement of each building block. Important trees were identified and preserved, with built forms arranged organically around them. The planning directs visitors through engaging programs while enjoying views of the forest and streams.',
    drawings: 'The project included detailed site plans, accommodation facility layouts, research lab plans, section drawings at multiple levels, and structural explorations using bamboo.',
    execution: 'As an academic project, this was developed as a comprehensive design proposal with full documentation ready for construction. The structural experiments with bamboo were particularly rewarding.',
    reflection: 'Working on this project deepened my appreciation for sustainable architecture. Designing with nature rather than against it produces spaces that feel alive and timeless.',
  },
  {
    id: 'auroville-cultural-zone',
    title: 'Auroville Cultural Zone',
    location: 'Auroville, Tamil Nadu',
    year: '2022',
    category: 'Academic',
    subCategory: 'Urban',
    role: 'Student Architect — Urban Context Studio',
    description: 'A master plan proposal for the Cultural and Industrial Zone of Auroville, respecting the vision of The Mother and Roger while proposing new cultural and industrial facilities.',
    heroImage: '/images/project-auroville-hero.jpg',
    images: ['/images/project-auroville-1.jpg', '/images/project-auroville-2.jpg'],
    concept: 'The design respected the essence of Auroville — the Crown Road, the existing green cover, and the philosophy of human unity. The proposal aimed to enhance the cultural and industrial fabric while preserving the natural landscape.',
    process: 'The process involved analyzing existing features, understanding the movement network, and proposing a zoning strategy that connects major nodes within walkable distances. The crown character was maintained and enhanced throughout the site.',
    drawings: 'Documentation included developable land analysis, zoning and building use programs, movement network plans, master plan proposals, and detailed sections through the crown road at key junctions.',
    execution: 'This academic project was developed as a complete urban design proposal with GIS-based analysis, area programs, and detailed master plan documentation.',
    reflection: 'Urban design requires thinking at multiple scales simultaneously. This project taught me to balance the big picture vision with the granular details that make a place livable.',
  },
  {
    id: 'kutch-research',
    title: 'Post Disaster Reconstruction',
    location: 'Kutch, Gujarat',
    year: '2023',
    category: 'Academic',
    subCategory: 'Research',
    role: 'Researcher — Bachelor Thesis',
    description: 'A research thesis evaluating post-disaster reconstruction of residential typologies in the Kutch region following the 2001 earthquake.',
    heroImage: '/images/project-kutch-hero.jpg',
    images: ['/images/project-kutch-1.jpg'],
    concept: 'The research explored how people adapted in their reconstructed houses over two decades, examining four cases around Bhuj that incorporated traditional wisdom with alternative technologies.',
    process: 'Field visits to Sardar Nagar, Rudra Mata, Hodka, and New Dudhai involved spatial analysis, interviews with residents, and documentation of adaptations. An analytical framework was developed for comparative study.',
    drawings: 'The thesis included detailed spatial analysis diagrams, comparative floor plans, time utilization studies, and material usage documentation.',
    execution: 'The research was conducted over six months with guidance from Prof. Parag Mistry, resulting in a comprehensive thesis document with findings on post-disaster housing adaptation.',
    reflection: 'This research changed my perspective on architecture. Buildings are not static objects — they evolve with the people who inhabit them. Understanding this dynamic relationship is essential for meaningful design.',
  },
];

export const categories = ['All', 'Professional', 'Academic', 'Other Works'] as const;
export type Category = (typeof categories)[number];

